// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37IDnmcBwek6mZLkzfGRKkWWViZh7ucg',
    appId: '1:167655734777:web:9157fe706c0d1d6cef1128',
    messagingSenderId: '167655734777',
    projectId: 'whatsapp-clone-542a5',
    authDomain: 'whatsapp-clone-542a5.firebaseapp.com',
    storageBucket: 'whatsapp-clone-542a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT81zxgD37BwdMrl3U7MNZ8knFafpYsro',
    appId: '1:167655734777:android:b20cf2e04aa03b28ef1128',
    messagingSenderId: '167655734777',
    projectId: 'whatsapp-clone-542a5',
    storageBucket: 'whatsapp-clone-542a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFyuvBmE5ynzTDSUy2Viam-NrrMtcMBTc',
    appId: '1:167655734777:ios:5838c946acb52df4ef1128',
    messagingSenderId: '167655734777',
    projectId: 'whatsapp-clone-542a5',
    storageBucket: 'whatsapp-clone-542a5.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
